### ISSUE TITLE
Install fails on Node 6.3.0

### ISSUE THREAD

**Issue by aendrew** [slackhq/node-slack-sdk#250]
I get the following on Node 6.3.0, no issue on 6.2.2:

```
In file included from ../src/batch.cc:5:
../node_modules/nan/nan.h:602:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:608:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:613:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:619:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/andrew.rininsland/Projects/github-project-manager-bot/node_modules/leveldown
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:leveldown@0.10.6 leveldown@0.10.6 install: `node-gyp rebuild`
npm WARN install:leveldown@0.10.6 Exit status 1
```

Not sure what's even using leveldown 0.10.6 — it doesn't show up in the dependency tree at all... 
¯\_(ツ)_/¯

**Comment by aendrew** [comment]
Err, it wasn't this package in the end with that dependency; though that was a bit weird... Never mind, my fault entirely!

**Comment by DEGoodmanWilson** [comment]
No worries!
