### ISSUE TITLE
npm install @slack/client receiving a 403 error

### ISSUE THREAD

**Issue by twellspring** [slackhq/node-slack-sdk#256]
I am trying to install the @slack/client via NPM, but it is returning with a 403 error.  As far as I can see, this is a public package so should not need authentication.

```
# npm install @slack/client --save
npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "@slack/client" "--save"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code E403

npm ERR! unregistered users are not allowed to access package @slack/client : @slack/client
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/web/node/chatops.80/npm-debug.log
```

**Comment by twellspring** [comment]
Here is debug
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@slack/client',
1 verbose cli   '--save' ]
2 info using npm@3.8.6
3 info using node@v5.12.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData @slack/client
8 silly fetchNamedPackageData @slack/client
9 silly mapToRegistry name @slack/client
10 silly mapToRegistry scope (from package name) @slack
11 verbose mapToRegistry no registry URL found in name for scope @slack
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry http://npm-ord.riskalyze.com/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: '@slack/client',
14 silly mapToRegistry   scope: '@slack',
14 silly mapToRegistry   name: '@slack/client',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri http://npm-ord.riskalyze.com/@slack%2fclient
16 verbose request uri http://npm-ord.riskalyze.com/@slack%2fclient
17 verbose request no auth needed
18 info attempt registry request try #1 at 4:21:58 PM
19 verbose request id b69706b50ce0abd0
20 http request GET http://npm-ord.riskalyze.com/@slack%2fclient
21 http 403 http://npm-ord.riskalyze.com/@slack%2fclient
22 verbose headers { 'x-powered-by': 'Sinopia/1.4.0',
22 verbose headers   'content-type': 'application/json; charset=utf-8',
22 verbose headers   'content-length': '84',
22 verbose headers   etag: 'W/"54-d795a792"',
22 verbose headers   vary: 'Accept-Encoding',
22 verbose headers   'x-status-cat': 'http://flic.kr/p/aV6jFK',
22 verbose headers   date: 'Mon, 25 Jul 2016 16:21:58 GMT',
22 verbose headers   connection: 'keep-alive' }
23 silly get cb [ 403,
23 silly get   { 'x-powered-by': 'Sinopia/1.4.0',
23 silly get     'content-type': 'application/json; charset=utf-8',
23 silly get     'content-length': '84',
23 silly get     etag: 'W/"54-d795a792"',
23 silly get     vary: 'Accept-Encoding',
23 silly get     'x-status-cat': 'http://flic.kr/p/aV6jFK',
23 silly get     date: 'Mon, 25 Jul 2016 16:21:58 GMT',
23 silly get     connection: 'keep-alive' } ]
24 silly fetchPackageMetaData Error: unregistered users are not allowed to access package @slack/client : @slack/client
24 silly fetchPackageMetaData     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
24 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
24 silly fetchPackageMetaData     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
24 silly fetchPackageMetaData     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:199:22)
24 silly fetchPackageMetaData     at emitTwo (events.js:100:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:185:7)
24 silly fetchPackageMetaData     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1036:10)
24 silly fetchPackageMetaData     at emitOne (events.js:95:20)
24 silly fetchPackageMetaData     at Request.emit (events.js:182:7)
24 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:963:12)
24 silly fetchPackageMetaData  error for @slack/client { [Error: unregistered users are not allowed to access package @slack/client : @slack/client] pkgid: '@slack/client', statusCode: 403, code: 'E403' }
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Starting
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: unregistered users are not allowed to access package @slack/client : @slack/client
30 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
30 verbose stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
30 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
30 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:199:22)
30 verbose stack     at emitTwo (events.js:100:13)
30 verbose stack     at Request.emit (events.js:185:7)
30 verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1036:10)
30 verbose stack     at emitOne (events.js:95:20)
30 verbose stack     at Request.emit (events.js:182:7)
30 verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:963:12)
31 verbose statusCode 403
32 verbose pkgid @slack/client
33 verbose cwd /home/web/node/chatops.80
34 error Linux 3.13.0-79-generic
35 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "@slack/client" "--save"
36 error node v5.12.0
37 error npm  v3.8.6
38 error code E403
39 error unregistered users are not allowed to access package @slack/client : @slack/client
```

**Comment by DEGoodmanWilson** [comment]
Oh geez, I see the problem. I've pushed a new release, 3.5.2, which addresses this issue.

**Comment by DEGoodmanWilson** [comment]
I've verified it works with 3.5.3. Can you also verify?

**Comment by DEGoodmanWilson** [comment]
Looks like this is still an issue for the original reporter. @twellspring could you share concrete steps to reproduce? So far, I haven't been able to.

**Comment by twellspring** [comment]
Just tried it again and it is working now.
