### ISSUE TITLE
Unhandled exception when websockets disconnect

### ISSUE THREAD

**Issue by arbind** [slackhq/node-slack-sdk#269]
* [x ] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x ] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
> e.g. Description of the bug or feature

#### Intermittent in:
{node-slack-sdk} version: 2.0.6

#### Steps to reproduce:

1. This is an intermittent failure - it seems to happen every few days when WebSocket keep disconnecting for a few hours, then the issue goes away again, without any code changes on our end. (maybe it happens when new API code released?)

### Expected result:
> The WS exception should be caught and returned as an ERROR through a callback

### Actual result:
> The WS exception is uncaught and basically halts the running process

### Attachments:
> Stack Trace:
```
/code/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:181
    throw new Error('not opened');
          ^
Error: not opened
  at WebSocket.pong (/code/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:181:11)
  at RTMClient.handleWsPing (/code/node_modules/slack-client/lib/clients/rtm/client.js:466:13)
  at WebSocket.wrapper (/code/node_modules/slack-client/node_modules/lodash/index.js:3095:19)
  at WebSocket.EventEmitter.emit (events.js:98:17)
  at Receiver.onping (/code/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:859:10)
  at /code/node_modules/slack-client/node_modules/ws/lib/Receiver.js:740:14
  at Receiver.flush (/code/node_modules/slack-client/node_modules/ws/lib/Receiver.js:347:3)
  at Receiver.opcodes.9.finish (/code/node_modules/slack-client/node_modules/ws/lib/Receiver.js:743:12)
  at /code/node_modules/slack-client/node_modules/ws/lib/Receiver.js:731:31
  at Receiver.expectData (/code/node_modules/slack-client/node_modules/ws/lib/Receiver.js:163:5)
  at Receiver.opcodes.9.getData (/code/node_modules/slack-client/node_modules/ws/lib/Receiver.js:730:14)
  at Receiver.opcodes.9.start (/code/node_modules/slack-client/node_modules/ws/lib/Receiver.js:713:30)
  at Receiver.processPacket (/code/node_modules/slack-client/node_modules/ws/lib/Receiver.js:244:19)
  at Receiver.add (/code/node_modules/slack-client/node_modules/ws/lib/Receiver.js:103:24)
  at CleartextStream.realHandler (/code/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:825:20)
  at CleartextStream.EventEmitter.emit (events.js:95:17)
  at CleartextStream.<anonymous> (_stream_readable.js:746:14)
  at CleartextStream.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at _stream_readable.js:401:7
  at process._tickCallback (node.js:415:13)
```

This same anti-pattern seems to exist elsewhere in this library too.
Maybe have a look at all the places where `ws/lib/WebSocket.js` throws exceptions, catch them and return the error message through the callback. This would give the retry logic (which does work very well) a chance to reconnect once the sockets are back up - otherwise the unhandled exception halts the client execution.

**Comment by DEGoodmanWilson** [comment]
Version 2.0.6 is quite old—have you checked to see that this issue still exists in the latest version (3.5.4 as of just now)?

**Comment by arbind** [comment]
Oh yea - that would prolly help!
Will integrate the latest in and keep an eye on it.

Thanks much.
